# Generated by Django 4.1.13 on 2024-07-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='label_color',
            field=models.CharField(default='#6aa84f', max_length=10),
        ),
    ]
