# Generated by Django 4.1.13 on 2024-07-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carservice_label_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
